id = "kiro-theme"
name = "Kiro Theme"
version = "0.1.0"
schema_version = 1
authors = ["MrPancakes39"]
description = "Kiro's dark and light color themes, ported to Zed"
repository = "https://github.com/MrPancakes39/kiro-zed-theme"
